apiVersion: v1
kind: Pod
metadata:
  labels:
    project: roboshop
    purpose: multi_container
spec:
  containers: 
    - name: nginx
      image: nginx
    - name: almalinux
      image: almalinux
      command: ["sleep", "1000"]