apiVersion: v1
kind: Pod 
metadata: 
  name: pod-config
  labels:
    project: roboshop
    purpose: pod-configmap-ref
spec: 
  containers:
   - name: nginx
     image: nginx
     envFrom:
      - configMapRef:
        - name: configmap-pod-ref