apiVersion: v1
kind: Service
metadata:
  name: "statefulset-headless"
  labels:
    purpose: "headless-service-demo"
spec:
  clusterIP: none
  selector:
    project: roboshop
    env: dev
    component: statefulset
  ports: 
  - port: 80
    name: web

---

apiVersion: v1 
kind: Service
metadata:
  name: "statefulset-service"
  labels:
    purpose: statefulset-service-demo
spec: 
  selector:
    project: roboshop
    env: dev
    component: statefulset
  ports: 
  - port: 80
    name: web


---

apiVersion: apps/v1
kind: Statefulset
metadata:
  name: statefulset-pod
  labels:
    purpose: statefulset-pod-label
spec:
  replicas: 3
  selector:
    matchLabels:
      project: roboshop
      env: dev
      component: statefulset 
  seviceName: "statefulset-headless"
  template:
    metadata:
      labels:
        project: roboshop
        env: dev
        component: statefulset
    spec: 
      containers:
        - name: nginx
          image: nginx 
          volumeMounts:
          - name: "statefulset-volume"
            mountPath: /usr/share/nginx/html
  volumeClaimTemplates: 
    metadata:
      name: "statefulset-volume"        
    spec:
      storageClassName: "efs-sc"
      accessModes: ["ReadWriteOnce"]
      resources:
        request:
          - storage: 1Gi