kind: StorageClass
apiVersion: storage.k8s.io/v1
metadata:
  name: efs-sc
provisioner: efs.csi.aws.com
reclaimPolicy: Retain 
parameters:
  provisioningMode: efs-ap
  fileSystemId: fs-024f1be6dc47887cd
  directoryPerms: "700"
  basePath: "/roboshop" # optional