apiVersion: apps/v1
kind: Deployment
metadata:
  name: mysql-secret
  labels: 
    purpose: mysql-secret-demo
spec: 
  replicas: 1
  selector:
    matchLabels:
      project: roboshop
      component: mysql-secret
  template:
    metadata:
      labels: 
        project: roboshop
        component: mysql-secret
    spec:
      containers:
        - name: mysql
          image: yadaveshnithin/mysql:v1 

--- 

apiVersion: v1 
kind: Service
metadata:
  name: mysql-secret-service
  labels: 
    purpose: mysql-secret-demo
spec:
  selector:
    project: roboshop
    component: mysql-secret
  ports: 
  - protocol: TCP 
    port: 3306
    targetPort: 3306

