apiVersion: apps/v1
kind: Deployment
metadata:
  name: mysql-secret
  namespace: roboshop
  labels: 
    purpose: mysql-secret-demo
spec: 
  replicas: 1
  selector:
    matchLabels:
      project: roboshop
      component: mysql-secret
  template:
    metadata:
      labels: 
        project: roboshop
        component: mysql-secret
    spec:
      serviceAccount: roboshop-mysql-secret-reader
      volumes:
        - name: mysql-secret-volume
          emptyDir: {}
      containers:
        - name: mysql
          image: yadaveshnithin/mysql:v3
          imagePullPolicy: Always
          volumeMounts:
            - mountPath: /tmp 
              name: mysql-secret-volume
      initContainers:
        - name: aws-cli-fetchsecrets
          image: amazon/aws-cli
          command:
            - sh 
            - -c 
            - |
                aws secretsmanager get-secret-value --secret-id roboshop/mysql/password --query SecretString --output text | jq -r .MYSQL_ROOT_PASSWORD > /tmp/mysql_root_password.txt
          volumeMounts:
            - mountPath: /tmp
              name: mysql-secret-volume


--- 

apiVersion: v1 
kind: Service
metadata:
  name: mysql-secret-service
  namespace: roboshop
  labels: 
    purpose: mysql-secret-demo
spec:
  selector:
    project: roboshop
    component: mysql-secret
  ports: 
  - protocol: TCP 
    port: 3306
    targetPort: 3306

