apiVersion: v1 
kind: Pod 
metadata:
  name: node-anti-affinity
  labels:
    purpose: node_affinity_hardrule
spec:
  affinity: 
    nodeAffinity: 
      requiredDuringSchedulingIgnoredDuringExecution:
        nodeSelectorTerms:
          - matchExpressions:
            - key: hardware
              operator: NotIn
              values:
              - gpu
  containers:
    - name: nginx 
      image: nginx 